# Copyright Keiron Dang. All Rights Reserved.

apiVersion: v2
name: common
version: 0.1.1
kubeVersion: 1.32.0
description: A Library Helm Chart for grouping common logic between charts. This chart is not deployable by itself.

type: library
appVersion: 1.0.0
sources:
  - https://github.com/keirond/container/tree/main/charts/common
maintainers:
  - name: Keiron Dang
    url: https://github.com/keirond
keywords:
  - common
  - helper