extraEnv:
  - name: AKHQ_CONFIGURATION
    value: |
      akhq:
        connections:
          kafka-cluster:
            properties:
              bootstrap.servers: "PLAINTEXT://kafka-broker-headless.kafka:9092"
            schema-registry:
              url: "http://schema-registry.kafka:8081"

ingress:
  enabled: true
  ingressClassName: nginx
  pathType: Prefix
  hosts:
    - akhq.167.254.190.2.nip.io