extraEnv:
  - name: AKHQ_CONFIGURATION
    value: |
      akhq:
        connections:
          kafka-cluster:
            properties:
              bootstrap.servers: "192.168.49.2:32094,192.168.49.2:32095,192.168.49.2:32096"
            schema-registry:
              url: ""
            connect:
              - name: connect
                url: ""

ingress:
  enabled: true
  pathType: Prefix
  hosts:
    - akhq.local