extraEnv:
  - name: AKHQ_CONFIGURATION
    value: |
      akhq:
        connections:
          kafka-cluster:
            properties:
              bootstrap.servers: "PLAINTEXT://kafka-headless.kafka:9092"
            schema-registry:
              url: "http://schema-registry.kafka:8081"

ingress:
  enabled: true
  pathType: Prefix
  hosts:
    - akhq.