dbUser:
  user: cassandra
  forcePassword: true
  password: cassandra

replicaCount: 3

resources:
  requests:
    cpu: 2
    memory: 8Gi
  limits:
    cpu: 3
    memory: 16Gi

persistence:
  enabled: true
  storageClass: longhorn
  commitStorageClass: longhorn
  size: 20Gi
  commitLogsize: 5Gi
  mountPath: /bitnami/cassandra

metrics:
  enabled: true