dbUser:
  user: cassandra
  forcePassword: true
  password: cassandra

replicaCount: 3

resources:
  requests:
    cpu: 1
    memory: 2Gi
  limits:
    cpu: 2
    memory: 4Gi

persistence:
  enabled: true
  storageClass: longhorn
  commitStorageClass: longhorn
  size: 40Gi
  commitLogsize: 20Gi
  mountPath: /bitnami/cassandra

metrics:
  enabled: true