dbUser:
  user: cassandra
  forcePassword: true
  password: cassandra

replicaCount: 3

resources:
  requests:
    cpu: 3
    memory: 4Gi
  limits:
    cpu: 4
    memory: 8Gi

persistence:
  enabled: true
  storageClass: longhorn
  commitStorageClass: longhorn
  size: 40Gi
  commitLogsize: 20Gi
  mountPath: /bitnami/cassandra

metrics:
  enabled: true