dbUser:
  user: cassandra
  forcePassword: true
  password: cassandra

replicaCount: 3

persistence:
  enabled: true
  storageClass: longhorn
  commitStorageClass: longhorn
  size: 20Gi
  commitLogsize: 5Gi
  mountPath: /bitnami/cassandra

metrics:
  enabled: true