apiVersion: v1
kind: Service
metadata:
  name: cassandra-lb
  namespace: cassandra
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: cassandra
  ports:
    - port: 9042
      targetPort: 9042
      protocol: TCP