kafka:
  enabled: false

replicaCount: 3

ingress:
  enabled: true
  ingressClassName: nginx
  pathType: Prefix
  hostname: schema-registry.167.254.190.2.nip.io

livenessProbe:
  enabled: false
readinessProbe:
  enabled: false

externalKafka:
  brokers:
    - PLAINTEXT://kafka-broker-headless.kafka:9092
  listener:
    protocol: PLAINTEXT