kafka:
  enabled: false

replicaCount: 3

ingress:
  enabled: true
  ingressClassName: nginx
  pathType: Prefix
  hostname: schema-registry.10.20.3.62.nip.io

externalKafka:
  brokers:
    - PLAINTEXT://kafka-broker-headless.kafka:9092
  listener:
    protocol: PLAINTEXT