apiVersion: v1
kind: Service
metadata:
  name: cassandra-external
  namespace: cassandra
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: cassandra
    app.kubernetes.io/name: cassandra
  ports:
    - port: 9042
      targetPort: 9042
      protocol: TCP
      nodePort: 30042