dbUser:
  user: cassandra
  forcePassword: true
  password: cassandra

replicaCount: 3

resources:
  requests:
    cpu: 8
    memory: 16Gi
  limits:
    cpu: 16
    memory: 32Gi

persistence:
  enabled: true
  storageClass: longhorn
  commitStorageClass: longhorn
  size: 100Gi
  commitLogsize: 30Gi
  mountPath: /bitnami/cassandra

metrics:
  enabled: true