# Bitnami Cilium

agent:
  containerPorts:
    health: 9879
    pprof: 6060
    hubblePeer: 4244
    metrics: 9962
    hubbleMetrics: 9965

  livenessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 30
    timeoutSeconds: 5
    failureThreshold: 10
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 30
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  startupProbe:
    enabled: false
    initialDelaySeconds: 5
    periodSeconds: 2
    timeoutSeconds: 1
    failureThreshold: 100
    successThreshold: 1

  resourcesPreset: "micro"

  cniPlugin:
    install: true


k8sServiceHost: ${HOST_IP}
k8sServicePort: 6443
kubeProxyReplacement: true

ipv4:
  enabled: true
ipv6:
  enabled: false