persistence:
  enabled: true
  storageClass: longhorn
  size: 1Gi

ingress:
  enabled: true
  ingressClassName: nginx
  pathType: Prefix
  hostname: kibana.167.254.190.2.nip.io

elasticsearch:
  hosts:
    - elasticsearch.elastic
  port: 9200

livenessProbe:
  enabled: false
readinessProbe:
  enabled: false