# Rook: Rook-Ceph

image:
  repository: docker.io/rook/ceph
  tag: v1.17.4
  pullPolicy: IfNotPresent

crds:
  enabled: true

resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 128Mi