apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: bgp-peering
  namespace: cni-plugin
spec:
  nodeSelector:
    matchLabels:
      bgp-ready: "true"
  virtualRouters:
    - localASN: 64512
      serviceSelector:
        matchExpressions:
          - key: "kubernetes.io/service-type"
            operator: In
            values:
              - LoadBalancer
      neighbors:
        - peerAddress: 192.0.2.1/32
          peerASN: 64513
