services:
  victoria-metrics:
    image: ${REGISTRY:-}victoriametrics/victoria-metrics:${VICTORIA_METRICS_VERSION:-latest}
    container_name: victoria-metrics
    ports:
      - "18428:8428"
    command:
      - "-httpListenAddr=:8428"
      - "-retentionPeriod=1"
      - "-storageDataPath=victoria-metrics-data"
      - "-enableMetadata"
      - "-loggerFormat=json"
      - "-promscrape.config=/etc/prometheus/prometheus.yaml"
    volumes:
      - victoriametrics-data:/victoria-metrics-data
      - ./prometheus_cfg.yaml:/etc/prometheus/prometheus.yaml:ro
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "4"
          memory: 6G
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        max_failure_ratio: 0.25
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        max_failure_ratio: 0.25
        order: start-first
    networks:
      - monitoring-network

volumes:
  victoriametrics-data:
    name: victoriametrics-data
    driver: local
networks:
  monitoring-network:
    name: monitoring-network
    driver: bridge
    external: true
