services:
  jaeger-collector:
    image: ${REGISTRY:-}jaegertracing/jaeger-collector:${JAEGER_VERSION:-latest}
    container_name: jaeger-collector
    ports:
      - "14317:4317"
      - "14318:4318"
      - "24267:14267"
      - "24268:14268"
      - "19411:9411"
      - "24250:14250"
    environment:
      - SPAN_STORAGE_TYPE=cassandra
    command:
      - "--collector.otlp.enabled=true"
      - "--collector.tags=jaeger-collector=true"
      - "--sampling.strategies-file=/etc/jaeger/sampling_strategies.json"
      - "--sampling.strategies-reload-interval=1m"
      - "--cassandra.servers=${CASSANDRA_SERVERS:-127.0.0.1}"
    volumes:
      - ./sampling_strategies.json:/etc/jaeger/sampling_strategies.json:ro
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1G
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        max_failure_ratio: 0.25
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        max_failure_ratio: 0.25
        order: start-first
    networks:
      - observability-network

networks:
  observability-network:
    name: observability-network
    driver: bridge
    external: true
