server:
  ingress:
    enabled: true
    ingressClassName: nginx
    pathType: Prefix
    hostname: prometheus.167.254.190.2.nip.io

  extraScrapeConfigs:
    - job_name: 'alarm-etl-job'
      static_configs:
        - targets: [ 'alarm-spk.ndl:8080' ]
    - job_name: 'kafka-jxm-exporter'
      static_configs:
        - targets: [ 'kafka-jmx-metrics.kafka:5556' ]
    - job_name: 'kafka-exporter'
      static_configs:
        - targets: [ 'kafka-exporter-prometheus-kafka-exporter.kafka:9308' ]
    - job_name: 'elasticsearch-exporter'
      static_configs:
        - targets: [ 'elasticsearch-metrics.elastic:9114' ]
    - job_name: 'cassandra-http-exporter'
      static_configs:
        - targets: [ 'cassandra.cassandra:8080' ]
    - job_name: 'cassandra-jxm-exporter'
      static_configs:
        - targets: [ 'cassandra.cassandra:5555' ]

  persistence:
    enabled: true
    storageClass: longhorn
    size: 20Gi