{
 "title": "container metrics",
 "tags": [
  "cadvisor",
  "container-metrics"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "data_source",
    "query": "victoriametrics-metrics-datasource"
   },
   {
    "name": "container_name",
    "query": {
     "query": "label_values(container_start_time_seconds,name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "container uptime",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{id!=\"/\", name=~\"${container_name}\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "cpu utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{id!=\"/\", name=~\"${container_name}\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{id!=\"/\", name=~\"${container_name}\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "network receive rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{id!=\"/\", name=~\"${container_name}\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "network transmit rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{id!=\"/\", name=~\"${container_name}\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "fs reads rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(container_fs_reads_bytes_total{id!=\"/\", name=~\"${container_name}\"}[1m])",
     "legendFormat": "{{name}} - {{device}}"
    }
   ]
  },
  {
   "title": "fs writes rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(container_fs_writes_bytes_total{id!=\"/\", name=~\"${container_name}\"}[1m])",
     "legendFormat": "{{name}} - {{device}}"
    }
   ]
  }
 ]
}