# Copyright Keiron Dang. All Rights Reserved.

apiVersion: v2
name: kafka
version: 0.1.0
kubeVersion: 1.32.0
description: Apache Kafka is a distributed streaming platform designed to build real-time pipelines and can be used as a message broker or as a replacement for a log aggregation solution for big data applications.

type: application
appVersion: 4.0.0
sources:
  - https://github.com/keirond/setup-container/tree/main/kubernetes/official/kafka
maintainers:
  - name: Keiron Dang
    url: https://github.com/keirond/setup-container
keywords:
  - kafka
  - streaming
  - producer
  - consumer
annotations:
  category: Infrastructure