# Copyright Keiron Dang. All Rights Reserved.

override:
  name: kafka
  namespace: infrastructure

broker:
  labels:
    test-key: test-value
  annotations:
    test-key: test-value
  matchLabels:
    test-key: test-value
  pod:
    labels:
      test-key: test-value
    annotations:
      test-key: test-value
  persistence:
    labels:
      test-key: test-value
    annotations:
      test-key: test-value
  log:
    labels:
      test-key: test-value
    annotations:
      test-key: test-value

  replicaCount: 1
  autoScaling:
    hpa:
      enabled: true
  podManagementPolicy: OrderedReady

service:
  type: ClusterIP
  clusterIP: ""

kafka:
  image:
