version: '3.8'

services:
  cassandra:
    image: nexus.fnc.reg/cassandra:3.11.6-debian-10-r100
    container_name: cassandra-vn
    ports:
      - "19042:9042"
    environment:
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
      - CASSANDRA_PASSWORD_SEEDER=yes
    volumes:
      - cassandra-data:/bitnami/cassandra
    restart: unless-stopped

volumes:
  cassandra-data:
    name: cassandra-data
    driver: local