version: '3.8'

services:
  cassandra:
    image: cassandra:5.0.0
    container_name: cassandra
    restart: unless-stopped
    volumes:
      - ./config/cassandra-config.yaml:/cassandra.yaml:rw
      - /home/baodh/cdc-lab/cassandra-data:/var/lib/cassandra
    network_mode: host
    command: bash -c "
      cp /cassandra.yaml /etc/cassandra/cassandra.yaml
      && cassandra -f -R"

networks:
  cassandra:
    name: cassandra
    driver: bridge

# sed -i 's/cdc_enabled: false/cdc_enabled: true/g' /etc/cassandra/cassandra.yaml
