version: '3.8'

services:
  cassandra:
    image: cassandra:5.0.0
    container_name: cassandra
    restart: always
    user: cassandra
    volumes:
      - ./config/cassandra-config.yaml:/cassandra.yaml:rw
      - /home/baodh/cdc-lab/cassandra-data:/var/lib/cassandra:rw
    network_mode: host


# sed -i 's/cdc_enabled: false/cdc_enabled: true/g' /etc/cassandra/cassandra.yaml
