version: '3.8'

services:
  keydb:
    image: eqalpha/keydb:x86_64_v6.3.4
    container_name: keydb
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - keydb_data:/data
    environment:
      - KEYDB_MAXMEMORY=4gb
      - KEYDB_MAXMEMORY_POLICY=allkeys-lru
    command: [
      "keydb-server",
      "--maxmemory", "4gb",
      "--maxmemory-policy", "allkeys-lru",
      "--save", ""
    ]
    networks:
      - keydb

volumes:
  keydb_data:
    name: keydb_data
    driver: local

networks:
  keydb:
    name: keydb
    driver: bridge
