image:
  registry: docker.io
  repository: bitnami/kafka
  tag: 4.0.0-debian-12-r5
  pullPolicy: IfNotPresent

clusterId: 2654a977-82cd-40e3-92e3-c5bd9692d540

listeners:
  client:
    name: CLIENT
    containerPort: 9092
    protocol: PLAINTEXT
    sslClientAuth: ""

  controller:
    name: CONTROLLER
    containerPort: 9093
    protocol: PLAINTEXT
    sslClientAuth: ""

  interbroker:
    name: INTERNAL
    containerPort: 9094
    protocol: PLAINTEXT
    sslClientAuth: ""

  external:
    name: EXTERNAL
    containerPort: 9095
    protocol: PLAINTEXT
    sslClientAuth: ""

controller:
  minId: 0
  replicaCount: 3
  controllerOnly: true
  persistence:
    enabled: true
    storageClass: standard
    size: 1Gi
    mountPath: /bitnami/kafka

broker:
  minId: 100
  replicaCount: 3
  persistence:
    enabled: true
    storageClass: standard
    size: 30Gi
    mountPath: /bitnami/kafka

externalAccess:
  enabled: true
  controller:
    service:
      type: NodePort
      nodePorts:
        - 31094
        - 31095
        - 31096
      externalIPs:
        - 10.20.3.62 # HOST_IP
        - 10.20.3.62 # HOST_IP
        - 10.20.3.62 # HOST_IP

  broker:
    service:
      type: NodePort
      nodePorts:
        - 32094
        - 32095
        - 32096
      externalIPs:
        - 10.20.3.62 # HOST_IP
        - 10.20.3.62 # HOST_IP
        - 10.20.3.62 # HOST_IP

metrics:
  jmx:
    enabled: true