clusterId: af73efac-2902-4e70-951f-48180aa81569

listeners:
  client:
    name: CLIENT
    containerPort: 9092
    protocol: PLAINTEXT

  controller:
    name: CONTROLLER
    containerPort: 9093
    protocol: PLAINTEXT

  interbroker:
    name: INTERNAL
    containerPort: 9094
    protocol: PLAINTEXT

  external:
    name: EXTERNAL
    containerPort: 9095
    protocol: PLAINTEXT

controller:
  minId: 0
  replicaCount: 3
  controllerOnly: true
  persistence:
    enabled: true
    storageClass: longhorn
    size: 5Gi
    mountPath: /bitnami/kafka
  resources:
    requests:
      cpu: 1
      memory: 2Gi
    limits:
      cpu: 2
      memory: 4Gi
broker:
  minId: 100
  replicaCount: 3
  persistence:
    enabled: true
    storageClass: longhorn
    size: 20Gi
    mountPath: /bitnami/kafka
  resources:
    requests:
       cpu: 1
       memory: 2Gi
    limits:
       cpu: 2
       memory: 4Gi

externalAccess:
  enabled: true
  controller:
    service:
      type: NodePort
      ports:
        external: 9092
      nodePorts:
        - 31094
        - 31095
        - 31096
      externalIPs:
        - 167.254.190.2 # HOST_IP
        - 167.254.190.2 # HOST_IP
        - 167.254.190.2 # HOST_IP
      useHostIPs: true

  broker:
    service:
      type: NodePort
      ports:
        external: 9092
      nodePorts:
        - 32094
        - 32095
        - 32096
      externalIPs:
        - 167.254.190.2 # HOST_IP
        - 167.254.190.2 # HOST_IP
        - 167.254.190.2 # HOST_IP
      useHostIPs: true

metrics:
  jmx:
    enabled: true