clusterId: af73efac-2902-4e70-951f-48180aa81569

listeners:
  client:
    name: CLIENT
    containerPort: 9092
    protocol: PLAINTEXT
    sslClientAuth: ""

  controller:
    name: CONTROLLER
    containerPort: 9093
    protocol: PLAINTEXT
    sslClientAuth: ""

  interbroker:
    name: INTERNAL
    containerPort: 9094
    protocol: PLAINTEXT
    sslClientAuth: ""

  external:
    name: EXTERNAL
    containerPort: 9095
    protocol: PLAINTEXT
    sslClientAuth: ""

controller:
  minId: 0
  replicaCount: 3
  controllerOnly: true
  persistence:
    enabled: true
    storageClass: longhorn
    size: 5Gi
    mountPath: /bitnami/kafka

broker:
  minId: 100
  replicaCount: 3
  persistence:
    enabled: true
    storageClass: longhorn
    size: 50Gi
    mountPath: /bitnami/kafka

externalAccess:
  enabled: true
  controller:
    service:
      type: NodePort
      nodePorts:
        - 31094
        - 31095
        - 31096
      externalIPs:
        - 167.254.190.2 # HOST_IP
        - 167.254.190.2 # HOST_IP
        - 167.254.190.2 # HOST_IP

  broker:
    service:
      type: NodePort
      nodePorts:
        - 32094
        - 32095
        - 32096
      externalIPs:
        - 167.254.190.2 # HOST_IP
        - 167.254.190.2 # HOST_IP
        - 167.254.190.2 # HOST_IP

metrics:
  jmx:
    enabled: true