# Longhorn: Longhorn

persistence:
  defaultClassReplicaCount: 1

csi:
  kubeletRootDir: /var/lib/kubelet

defaultSettings:
  defaultReplicaCount: 1
  defaultDataPath: /var/lib/docker/longhorn
  replicaAutoBalance: best-effort
  storageOverProvisioningPercentage: 100
  storageMinimalAvailablePercentage: 10
  storageReservedPercentageForDefaultDisk: 10

ingress:
  enabled: true
  ingressClassName: nginx
  pathType: Prefix
  host: longhorn.${API_SERVER_IP}.nip.io
