# Longhorn: Longhorn

persistence:
  defaultClassReplicaCount: 1

defaultSettings:
  defaultDataPath: /var/lib/docker/longhorn
  replicaAutoBalance: best-effort

ingress:
  enabled: true
  ingressClassName: nginx
  pathType: Prefix
  host: longhorn.167.254.190.2.nip.io
