#kibanaEnabled: false

ingress:
  enabled: true
  ingressClassName: nginx
  pathType: Prefix
  hostname: elasticsearch.167.254.190.2.nip.io

master:
  masterOnly: true
  replicaCount: 3
  persistence:
    enabled: true
    storageClass: longhorn
    size: 8Gi
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  resources:
    requests:
      cpu: 25m
      memory: 1Gi

data:
  replicaCount: 3
  persistence:
    enabled: true
    storageClass: longhorn
    size: 50Gi
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  resources:
    requests:
      cpu: 2
      memory: 8Gi
    limits:
      cpu: 3
      memory: 16Gi

coordinating:
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false

ingest:
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false

metrics:
  enabled: true