persistence:
  defaultClassReplicaCount: 1

defaultSettings:
  defaultDataPath: /export/longhorn

ingress:
  enabled: true
  ingressClassName: nginx
  pathType: Prefix
  host: longhorn.167.254.190.2.nip.io
