version: '3.8'

services:

  redis:
    image: redis:7.4.2
    container_name: std_redis
    restart: on-failure
    ports:
      - "6379:6379"
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
      - std_redis_data:/data
    command: [
      "redis-server",
      "/usr/local/etc/redis/redis.conf"
    ]
    networks:
      - std_redis
    deploy:
      resources:
        limits:
          memory: 4G

volumes:
  std_redis_data:
    name: std_redis_data
    driver: local

networks:
  std_redis:
    name: std_redis
    driver: bridge