# Bitnami: Harbor

# <service-name>.<namespace>.svc.<clusterDomain>
clusterDomain: cluster.local

adminPassword: ${ADMIN_PASSWORD}

ipFamily:
  ipv6:
    enabled: false
  ipv4:
    enabled: true

cache:
  enabled: false
  expireHours: 24
database:
  maxIdleConns: 100
  maxOpenConns: 900

service:
  type: LoadBalancer
  ports:
    http: 80
    https: 443

ingress:
  core:
    pathType: Prefix
    hostname: harbor.${HOST_IP}.nip.io
    ingressClassName: nginx

persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    registry:
      accessModes:
        - ReadWriteOnce
      size: 100Gi

portal:
  image:
    registry: docker.io
    repository: bitnami/harbor-portal
    tag: 2.13.1-debian-12-r2
    digest: ""
    pullPolicy: IfNotPresent
    pullSecrets: []
    
  replicaCount: 1
  service:
    ports:
      http: 80
      https: 443
  containerPorts:
    http: 8080
    https: 8443

  livenessProbe:
    enabled: true
  readinessProbe:
    enabled: true
  startupProbe:
    enabled: false

  resourcesPreset: "small"
  resources: {}

  networkPolicy:
    enabled: true
    allowExternal: true
    allowExternalEgress: true

core:
  image:
    registry: docker.io
    repository: bitnami/harbor-core
    tag: 2.13.1-debian-12-r7
    digest: ""
    pullPolicy: IfNotPresent
    pullSecrets: []

  replicaCount: 1
  service:
    ports:
      http: 80
      https: 443
      metrics: 8001
  containerPorts:
    http: 8080
    https: 8443
    metrics: 8001

  livenessProbe:
    enabled: true
  readinessProbe:
    enabled: true
  startupProbe:
    enabled: false

  resourcesPreset: "small"
  resources: {}

# TODO