# Bitnami: HAProxy

# <service-name>.<namespace>.svc.<clusterDomain>
clusterDomain: cluster.local

# HAProxy Service
service:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http

networkPolicy:
  enabled: true
  allowExternal: true
  allowExternalEgress: true

ingress:
  enabled: true
  pathType: Prefix
  hostname: haproxy.${HOST_IP}.nip.io
  path: /
  ingressClassName: ""

image:
  registry: docker.io
  repository: bitnami/haproxy
  tag: 3.2.1-debian-12-r0
  digest: ""
  pullPolicy: IfNotPresent
  pullSecrets: []

replicaCount: 3

livenessProbe:
  enabled: true
readinessProbe:
  enabled: true
startupProbe:
  enabled: false

resourcesPreset: "nano"
resources: {}

configuration: |
  global
    log stdout format raw local0
    maxconn 1024
  defaults
    log global
    timeout client 60s
    timeout connect 60s
    timeout server 60s
  frontend fe_main
    bind :8080
    default_backend be_main
  backend be_main
    server web1 10.0.0.1:8080 check

containerPorts:
  - name: http
    containerPort: 8080