{{/*Copyright Keiron Dang. All Rights Reserved.*/}}

{{- $replicaCount := int .Values.broker.replicaCount }}
{{- if gt $replicaCount 0 }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "kafka.svc-headless.name" . }}
spec:
  type: {{ .Values.service.type }}
{{- end}}