name: Publish Helm Chart to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch
        run: git fetch origin main

      - name: Configure git
        run: |
          git config --global user.name "Container Actions"
          git config --global user.email "actions@github.com"

      - name: Setup helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.9.0'

      - name: Detect changed charts
        id: changed-charts
        run: |
          echo "CHANGED_DIRS<<EOF" >> $GITHUB_OUTPUT
          git diff --name-only origin/main HEAD^ | grep '^charts/' | cut -d/ -f2 | sort -u | while read chart; do
            if [ -f "charts/$chart/Chart.yaml" ]; then
              echo "charts/$chart"
            fi
          done >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Package changed charts
        if: steps.changed-charts.outputs.CHANGED_DIRS != ''
        run: |
          mkdir -p package
          for dir in ${{ steps.changed-charts.outputs.CHANGED_DIRS }}; do
            helm package "$dir" --destination package
          done

      - name: Publish changed charts
        if: steps.changed-charts.outputs.CHANGED_DIRS != ''
        run: |
          git clone --branch main https://x-access-token:${TOKEN}@github.com/keirond/helm-charts.git
          cd helm-charts
          cp ../package/*.tgz .
          helm repo index . --url https://keirond.github.io/helm-charts
          git add .
          git commit -m "Publish Helm charts" || echo "No changes to commit"
          git push origin main
        env:
          TOKEN: ${{ secrets.HELM_REPO_TOKEN }}