name: Publish Helm Chart to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Package charts
        run: |
          mkdir -p package
          for dir in chart/*/; do
            helm package "$dir" --destination package
          done

      - name: Publish Helm Charts
        uses: |
          git clone --branch main https://x-access-token:${{ secrets.HELM_REPO_TOKEN }}@github.com/keirond/helm-charts.git
          
          cd helm-charts
          cp ../package/*.tgz .
          helm repo index . --url https://keirond.github.io/helm-charts
          
          git add .
          git commit -m "Publish Helm charts"
          git push origin main